### ISSUE TITLE
Improve usage section in readme

### ISSUE THREAD

**Issue by SanketDG** [ssundarraj/image-resize#1]
It's just said `image-resize input_file.jpg` which isn't the exact input. You have to later add arguments. It's better if you did explain the various arguements in the readme for ease of use.

**Comment by ssundarraj** [comment]
@SanketDG Thanks for pointing this out. I'll update the readme.

**Comment by ssundarraj** [comment]
@SanketDG I've updated it. Let me know if further clarity would be of help.

**Comment by SanketDG** [comment]
I think it is clarified now. :)

**Comment by ssundarraj** [comment]
@SanketDG  Thanks again.
